:imagesdir: ../assets/images
:toc:
= Discovering Lab Environments and Product Insights

In this workshop, we have installed and configured several products to demonstrate the Event-Driven capabilities effectively. To complete the workshop, we will explore the products used by opening a few browser tabs as listed below:

* VS Code Server
* Red Hat Ansible Automation Platform
* Red Hat OpenShift Console
* Red Hat Hybrid Cloud Console
:numbers:

== VS Code Server
. Log in to the VS Code Server, where we will use the integrated terminal to execute oc commands. These commands will create OpenShift resources, which will subsequently trigger events during the lab exercise.
+
****
[upperalpha]
.. Login Details:
* *VS Code Server URL:* https://bastion.{guid}{subdomain_base_suffix}[window=_blank]
* *Password:* {bastion_ssh_password}
****

== Red Hat OpenShift Console
. Optionally, you can log in to the Red Hat OpenShift Console to explore the resources that are already installed and configured. This also allows you to verify the impact of the Event-Driven triggers that will occur in the upcoming labs.
+
****
[upperalpha]
.. Login Details:
* *Red Hat OpenShift Console URL:* {openshift_cluster_console_url}[window=_blank]
* Click *htpasswd_provider* then enter username & password
* *Username:* {openshift_cluster_admin_username}
* *Password:* {penshift_cluster_admin_password}
****

== Red Hat Hybrid Cloud Console
. Log in to the Red Hat Hybrid Cloud Console, as we will use it to create Event-Driven Integrations, Notifications, and Triggers in the upcoming labs.
+
****
[upperalpha]
.. Log details:
* *Console URL:* {hybrid_cloud_url}
* *Username:*	{hybrid_cloud_username}
* *Password:* {hybrid_cloud_password}

+
NOTE: This user has limited permissions in the Red Hat Hybrid Cloud Console. While they can complete all the activities in this lab exercise, certain capabilities may not be accessible. This is by design to ensure a positive and consistent lab experience for all users.
****

== Red Hat Ansible Automation Platform
. Log in to Ansible Automation Platform 2.5 to explore Automation Execution and Automation Decisions, which will play a key role in the Event-Driven Ansible triggers in the upcoming labs.
+
****
[upperalpha]
.. Login Details:
* *Ansible Automation Platfrom URL:* {aap_controller_web_url}[window=_blank]
* *Username:* {aap_controller_admin_user}
* *Password:* {aap_controller_admin_password}
****

=== Explore Automation Execution
Let's take a moment to explore the Automation Execution Environment that has already been configured for this lab. This step is entirely optional, and you may skip it and proceed to the next page. However, gaining an understanding of the pre-configured setup can be helpful for the upcoming lab exercises.

. Automation Execution Projects, The following projects have been pre-configured for this lab. For more details, navigate to *Automation Execution → Projects*.
+
****
[upperalpha]
.. *RH Insights project* - This project is configured to work with Insight events in the Job Template.
.. *event-driven-ansible* - This project is configured to work with OpenShift events in the Job Template.

****

. Credentials
Go to Automation Execution → Infrastructure → Credentials 
.. Openshift Credentials
.. Host Credentials
.. RH Insights Lab User

. Inventories
Go to Automation Execution → Infrastructure → Inventories
.. RH Insights inventory
.. Click sources tab 
.. Insights source

. Hosts
Go to Automation Execution → Infrastructure → Hosts

. Templates
Go to Automation Execution → Templates
.. create-volume-snapshot
.. patch-route-with-cert
.. set-resource-quota-on-namespace
.. handle-malware-detection

=== Explore Automation Decision
. Projects
Go to Automation Decisions → Projects 
.. OpenShift Event Rulebooks
.. RH Insights

. Credentials
Go to Automation Decisions → Infrastructure → Credentials 
.. RHInsights
.. registry.redhat.io
.. RH AAP Credential

. Decision Environments
Go to Automation Decisions → Decision Environments
.. AAP2.5 - OCP4 Custom Decision

. Event Steams
Go to Automation Decisions → Event Streams
.. Red Hat Insights Event Stream

. Rulebook Activations
Go to Automation Decisions → Rulebook Activations
.. Create Volume Snapshot
.. Set Resource Quota On Namespace
.. Patch Route With Cert

