:imagesdir: ../assets/images
:toc:

= Discovering Lab Environments and Product Insights

In this workshop, we have installed and pre-configured several products to demonstrate the Event-Driven capabilities effectively. To complete the workshop, we will explore the products used by opening a few browser tabs as listed below:

* VS Code Server
* Red Hat Ansible Automation Platform
* Red Hat OpenShift Console
* Red Hat Hybrid Cloud Console

:sectnums:
== VS Code Server
[upperalpha]

. Log in to the VS Code Server, where we will use the integrated terminal to execute oc commands. These commands will create OpenShift resources, which will subsequently trigger events during the lab exercise.
+
****
// .. Login Details:
* *VS Code Server URL:* https://bastion.{guid}{subdomain_base_suffix}[window=_blank]
* *Password:* {bastion_ssh_password}
****

== Red Hat OpenShift Console
[upperalpha]

. Optionally, you can log in to the Red Hat OpenShift Console to explore the resources that are already installed and configured. This also allows you to verify the impact of the Event-Driven triggers that will occur in the upcoming labs.
+
****
// .. Login Details:
* *Red Hat OpenShift Console URL:* {openshift_cluster_console_url}[window=_blank]
* Click *htpasswd_provider* then enter username & password
* *Username:* {openshift_cluster_admin_username}
* *Password:* {openshift_cluster_admin_password}
****

== Red Hat Hybrid Cloud Console
[upperalpha]
. Log in to the Red Hat Hybrid Cloud Console, as we will use it to create Event-Driven Integrations, Notifications, and Triggers in the upcoming labs.
+
****

// .. Log details:
* *Console URL:* {hybrid_cloud_url}
* *Username:*	{hybrid_cloud_username}
* *Password:* {hybrid_cloud_password}

+
NOTE: This user has limited permissions in the Red Hat Hybrid Cloud Console. While they can complete all the activities in this lab exercise, certain capabilities may not be accessible. This is by design to ensure a positive and consistent lab experience for all users.
****

== Red Hat Ansible Automation Platform
[upperalpha]

. Log in to Ansible Automation Platform 2.5 to explore Automation Execution and Automation Decisions, which will play a key role in the Event-Driven Ansible triggers in the upcoming labs.
+
****
[upperalpha]
// .. Login Details:
* *Ansible Automation Platfrom URL:* {aap_controller_web_url}[window=_blank]
* *Username:* {aap_controller_admin_user}
* *Password:* {aap_controller_admin_password}
****

=== Explore Automation Execution
[upperalpha]

Let's take a moment to explore the Automation Execution that has already been configured for this lab. 

WARNING: Please don't skip this section! There are some steps you need to take below. 

[upperalpha]

. The following projects have been pre-configured for this lab. For more details, navigate to *Automation Execution → Projects*.
+
****
.. *RH Insights project* - This project is configured to work with Insight events in the Job Template.
.. *event-driven-ansible* - This project is configured to work with OpenShift events in the Job Template.

****

. The following credentials have been pre-configured for this lab. For more details, navigate to *Automation Execution → Infrastructure → Credentials*.
+
****
[upperalpha]
.. *Openshift Credentials* - Contains Red Hat OpenShift API Bearer Token.
.. *Host Credentials* - Machine credentials to connect with nodes.
.. *RH Insights Lab User* - Red Hat Hybrid Cloud Console credentials to connect with Red Hat Insights.
****

. The following inventories have been pre-configured for this lab. For more details, navigate to *Automation Execution → Infrastructure → Inventories*.
+
IMPORTANT: Please don't skip this section!
+
****
[upperalpha]
.. *RH Insights inventory* - This is a Dynamic Inventory with Red Hat Insights as its source, fetching all connected hosts into the inventory.
.. Click the *RH Insights inventory* - To explore about the inventory
.. Then click *Hosts* tab - At this stage, you will see no other hosts.
.. Now click *Sources* tab and then click the *rocket icon* - To initiate the inventory update.
.. Once status is changed to *Success* return to *Hosts* tab - To view the entries from the Red Hat Insights inventory, you may need to wait for a while or refresh the page to see the updated information.
****

. The following templates have been pre-configured for this lab. For more details, navigate to *Automation Execution → Templates*.
+
****
[upperalpha] 
.. *create-volume-snapshot* - This Job Template is triggered whenever a new Persistent Volume Claim (PVC) is created in Red Hat OpenShift, automatically creating a snapshot for the PVC.
.. *patch-route-with-cert* - This Job Template is triggered whenever a new unsecured route is created in Red Hat OpenShift, enabling the implementation of an SSL certificate for the route.
.. *set-resource-quota-on-namespace* - This Job Template is triggered whenever a new namespace is created in Red Hat OpenShift, automatically setting the resource quota for the namespace. 
.. *handle-malware-detection* - This Job Template is triggered whenever Red Hat Insights detects malware on a node, initiating the necessary remediation actions.
****

=== Explore Automation Decision
[upperalpha]

Let's take a moment to explore the Automation Decision that has already been configured for this lab. This step is entirely optional, and you may skip it and proceed to the next page. However, gaining an understanding of the pre-configured setup can be helpful for the upcoming lab exercises.

[upperalpha]

. The following projects have been pre-configured for this lab. For more details, navigate to *Automation Decisions → Projects*.
+
****
[upperalpha] 
.. *OpenShift Event Rulebooks* - This project contains Event-Driven Ansible rulebooks designed to process Red Hat OpenShift events.
.. *RH Insights* - This project contains Event-Driven Ansible rulebooks designed to process Insights events.
****

. The following credentials have been pre-configured for this lab. For more details, navigate to *Automation Decisions → Infrastructure → Credentials*.
+
****
[upperalpha]
.. *RHInsights* - Red Hat Insight token to connect with Red Hat Insights.
.. *registry.redhat.io* -  Registry credentials.
.. *RH AAP Credential* - Red Hat Ansible Automation Platform credentials.
****

. The following Decision Environments have been pre-configured for this lab. For more details, navigate to *Automation Decisions → Decision Environments*.
+
****
[upperalpha]
.. *Default Decision Environment* - is the default environment that uses the registry.redhat.io/ansible-automation-platform-25/de-supported-rhel8:latest image.
.. *AAP2.5 - OCP4 Custom Decision* - is a custom decision environment built from the default environment. This decsion environment includes a custom Event-Driven Ansible plugin, k8s, and is hosted on quay.io/mitsharm/eda/de-for-ocp-aap-25:latest.
****

. The following Event Streams have been pre-configured for this lab. For more details, navigate to *Automation Decisions → Event Streams*. 
+
****
[upperalpha]
.. *Red Hat Insights Event Stream* - is an event stream created to integrate Red Hat Hybrid Cloud with a Rulebook Activation.
****

. The following Rulebook Activations have been pre-configured for this lab. For more details, navigate to *Automation Decisions → Rulebook Activations*.
+
****
[upperalpha]
.. *Create Volume Snapshot* - This Rulebook Activation triggers an action whenever a new Persistent Volume Claim (PVC) is created in Red Hat OpenShift.
.. *Set Resource Quota On Namespace* - This Rulebook Activation triggers an action whenever a new unsecured route is created in Red Hat OpenShift.
.. *Patch Route With Cert* -  This Rulebook Activation triggers an action whenever a new namespace is created in Red Hat OpenShift.
****

