= Red Hat Ansible Automation Platform

== Explore Automation Controller

. Log in to Ansible Automation Platform 2.5 using the provided URL, username, and password to access the dashboard.
+
****
[upperalpha]
.. Login Details:
* *Ansible Automation Platfrom URL:* {aap_controller_web_url}[window=_blank]
* *Username:* {aap_controller_admin_user}
* *Password:* {aap_controller_admin_password}


****

. Explore the Automation Controller inventory to review and manage available hosts and resources.
+
****
[upperalpha]
.. Navigate to *Automation Execution → Infrastructure → Hosts* to view and manage host details.
+
NOTE: At this stage, you will only see localhost listed and no other hosts

.. Sync the inventory to ensure it is up-to-date with the latest hosts.
+
* Go to *Inventories*.
* Select the *RH Insights Inventory*.
* Click the *sources* tab. 
* Click the rocket icon next to *Insights source* to initiate the inventory update.

+
NOTE: The status will briefly show Running and then change to Success once the update is complete. After completion, return to the Hosts page to view the entries from the Red Hat Insights inventory.
****

. Explore the Automation Controller Job Template to view, configure, and manage automation jobs for streamlined execution and management of tasks.
+
****
[upperalpha]
.. Navigate to *Automation Execution → Templates* to view and manage Job Templates.
+
NOTE: You will see an existing *Malware Detection Job template*, which will be triggered when malware is detected. For simplicity, we’ve used a basic “Hello World” task, as we prefer to leave the specific handling of malware in your environment to your discretion.

.. Click on the handle-malware-detection job template to explore the following details:
+
* *Name:* handle-malware-detection
* *Description:* Hello World Placeholder
* *Job Type:* Run
* *Inventory:* RH Insights Inventory
* *Project:* Demo Project 
* *Playbook:* hello_world.yml
* *Execution Environment:* Default execution environment
* *Credentials:* Demo Credential
+
NOTE: By selecting the RH Insights Inventory, you can view the playbooks generated by Insights. However, Insights does not generate a specific playbook for handling malware, as the approach to malware management should be defined based on your organization's procedures.

****
