= Red Hat Ansible Automation Platform

== Explore Automation Controller

. Log into Ansible Automation Platform 2.5
+
****
[upperalpha]
.. Find the login details for accessing Ansible Automation Platform 2.5 below:
... *Ansible Automation Platfrom URL:* {aap_controller_web_url}[window=_blank]
... *Username:* {aap_controller_admin_user}
... *Password:* {aap_controller_admin_password}
****

. Explore Automation Controller Inventory

+
****
[upperalpha]
.. Go to *Automation Execution → Infrastructure → Hosts*
+
NOTE: At this point you will only see localhost listed - no other hosts.

.. You need to sync the inventory.  
... Go to Inventories.
... Select the RH Insights Inventory.
... Click the sources tab. 
... Click launch inventory update (The rocket icon to the right of “Insights source”).

+
NOTE: You will see the status change to Running briefly, then Success once completed. Once completed, return to the Hosts page. You should now see several entries from the RH Insights Inventory.

****

. Explore Automation Controller Job Template
+
****
[upperalpha]
.. Go to *Automation Execution → Templates*
+
NOTE: You will see exiting *Malware Detection Job* job template.  This is what will get triggered when malware is detected. We have just used a simple “Hello World” as we don't want to tell you HOW to deal with Malware in your environment.

.. Click The *handle-malware-detection* job template to explore following:

... Name: handle-malware-detection
... Description: Hello World Placeholder
... Job Type: Run
... Inventory: RH Insights Inventory
... Project: Demo Project 
... Playbook: hello_world.yml
... Execution Environment: Default execution environment
... Credentials: Demo Credential
+
NOTE: If you select the RH Insights Inventory you can see playbooks that are generated in Insights.  Insights does not generate a playbook for handling Malware as that is up to your organizational procedures to define.

****
